# Generated by Django 6.0.4 on 2026-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaggiodato',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='messaggiodato',
            name='canale',
            field=models.IntegerField(default=20),
        ),
    ]
