# Generated by Django 6.0.4 on 2026-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_messaggiodato_timestamp_messaggiodato_canale'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggiodato',
            name='ToT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='messaggiodato',
            name='canale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messaggiodato',
            name='valore',
            field=models.FloatField(default=0),
        ),
    ]
