# Generated by Django 6.0.4 on 2026-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_messaggiodato_tot_alter_messaggiodato_canale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaggiodato',
            name='valore',
        ),
        migrations.AddField(
            model_name='messaggiodato',
            name='ADC',
            field=models.IntegerField(default=0),
        ),
    ]
