# Generated by Django 6.0.4 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_messaggiodato_valore_messaggiodato_adc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggiodato',
            name='ToT',
            field=models.IntegerField(default=0),
        ),
    ]
